spring.application.name=A1pi2_getWay1




# ===== Route to Zomato Service =====
spring.cloud.gateway.routes[0].id=zomato-service
spring.cloud.gateway.routes[0].uri=http://localhost:7777
spring.cloud.gateway.routes[0].predicates[0]=Path=/zomato/**

# ===== Route to Swiy Service =====
spring.cloud.gateway.routes[1].id=swiy-service
spring.cloud.gateway.routes[1].uri=http://localhost:1111
spring.cloud.gateway.routes[1].predicates[0]=Path=/swiy/**

server.port=9091