spring.application.name=Api_getWay

spring.cloud.gateway.routes[0].id=zomzto
spring.cloud.gateway.routes[0].uri=http://localhost:7777
spring.cloud.gateway.routes[0].predicates=Path=/zomato/**

spring.cloud.gateway.routes[1].id=zomzto
spring.cloud.gateway.routes[1].uri=http://localhost:1111
spring.cloud.gateway.routes[1].predicates=Path=/swiy/**



server.port=9090